### ISSUE TITLE
Error when a chromosome in the pairs file is not in the HiC matrix

### ISSUE THREAD

**Issue by MariaRig** [vaquerizaslab/chess#1]
When I run `chess sim`, I get this error, probably because my pairs file contains chromosomes that aren't in the Hi-C data. The problem is that it crashes after running for some hours, so maybe `chess sim` could issue a warning instead, or warn of the future crash earlier? 
Thank you 

```
2020-04-24 13:47:35,830 INFO Running 'chess sim pos_1.sparse pos_1.regions neg_1.sparse neg_1.regions grch38.pairs chess_results/sample_1_pos_vs_neg_comparison.tsv'
2020-04-24 13:47:43,779 INFO [MAIN]: Loading and indexing Hi-C regions
2020-04-24 13:49:16,673 INFO [MAIN]: Loading Hi-C contacts
2020-04-24 13:49:16,674 INFO [MAIN]: Converting to observed / expected
2020-04-24 16:28:18,060 INFO [MAIN]: Loading region pairs
2020-04-24 16:28:43,954 INFO Launching workers
2020-04-24 16:28:49,646 INFO Submitting pairs for comparison
2020-04-24 20:46:30,866 ERROR Worker 8862c7f9-5e90-4938-a8a0-3bb337d4d4c1 encountered a problem: 'chr5_GL339449v2_alt'
Traceback (most recent call last):
  File "/home/mrigaud/.local/bin/chess", line 982, in <module>
    Chess()
  File "/home/mrigaud/.local/bin/chess", line 78, in __init__
    getattr(self, args.command)([sys.argv[0]] + sys.argv[option_ix:])
  File "/home/mrigaud/.local/bin/chess", line 274, in sim
    raise out
KeyError: 'chr5_GL339449v2_alt'
```

**Comment by nickmachnik** [comment]
Thank you for submitting this issue and for the suggestion. There is now a warning message if the pairs file contains chromosomes that are not defined in the provided contact data. The respective pairs are excluded from the analysis.

This is implemented in the latest version on master, you can just pull and reinstall. Please be aware that in the meantime the command line interface has also changed slightly, as CHESS now accepts fan-c, juicer and cooler files as input. This is not released to PyPI yet, but will be as soon as we will have tested this sufficiently.
