### ISSUE TITLE
'Series' object has no attribute 'bias' in `chess sim`

### ISSUE THREAD

**Issue by nickmachnik** [vaquerizaslab/chess#3]
thanks a lot.

when I ran sim command, I got this error:
AttributeError: 'Series' object has no attribute 'bias'.
the version of pandas is pandas-0.25.3.
do you think that the pandas should be degraded to pandas (0.22.0)?
best,

_Originally posted by @benxiahu in https://github.com/vaquerizaslab/chess/issues/2#issuecomment-712945286_

**Comment by nickmachnik** [comment]
Could you please post the full error message?

**Comment by benxiahu** [comment]
2020-10-20 11:39:48,248 INFO Loading reference contact data
2020-10-20 11:39:49,601 INFO Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
Traceback (most recent call last):
  File "/nas/longleaf/home/hubenxia/anaconda2/envs/python36/bin/chess", line 548, in <module>
    Chess()
  File "/nas/longleaf/home/hubenxia/anaconda2/envs/python36/bin/chess", line 76, in __init__
    getattr(self, args.command)([sys.argv[0]] + sys.argv[option_ix:])
  File "/nas/longleaf/home/hubenxia/anaconda2/envs/python36/bin/chess", line 119, in sim
    reference_matrix_file, reference_regions_file)
  File "/nas/longleaf/home/hubenxia/anaconda2/envs/python36/lib/python3.6/site-packages/chess/helpers.py", line 554, in load_contacts
    edges = oe_edges_dict_from_fanc(reference_loaded)
  File "/nas/longleaf/home/hubenxia/anaconda2/envs/python36/lib/python3.6/site-packages/chess/helpers.py", line 389, in oe_edges_dict_from_fanc
    for e in hic.edges(oe=True, lazy=True):
  File "/nas/longleaf/home/hubenxia/anaconda2/envs/python36/lib/python3.6/site-packages/fanc/matrix.py", line 696, in __call__
    bias = self._regions_pairs.bias_vector()
  File "/nas/longleaf/home/hubenxia/anaconda2/envs/python36/lib/python3.6/site-packages/fanc/compatibility/cooler.py", line 456, in bias_vector
    return np.array([r.bias for r in self.regions(lazy=True)])
  File "/nas/longleaf/home/hubenxia/anaconda2/envs/python36/lib/python3.6/site-packages/fanc/compatibility/cooler.py", line 456, in <listcomp>
    return np.array([r.bias for r in self.regions(lazy=True)])
  File "/nas/longleaf/home/hubenxia/anaconda2/envs/python36/lib/python3.6/site-packages/fanc/compatibility/cooler.py", line 221, in __getattr__
    return getattr(self._series, item)
  File "/nas/longleaf/home/hubenxia/anaconda2/envs/python36/lib/python3.6/site-packages/pandas/core/generic.py", line 5179, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'bias'

**Comment by nickmachnik** [comment]
Alright, this looks like an error with dealing with the cooler format in fanc to me. Could you please quickly check whether you get the same error with a new pandas version (`pip install pandas --upgrade`)? 0.25.3 is quite old, the latest is 1.1.3.

**Comment by kaukrise** [comment]
Hi, this looks like a FAN-C error, could you post the output of `fanc -V` from the command line, please?

**Comment by benxiahu** [comment]
fanc: '0.9.4'

**Comment by benxiahu** [comment]
> Alright, this looks like an error with dealing with the cooler format in fanc to me. Could you please quickly check whether you get the same error with a new pandas version (`pip install pandas --upgrade`)? 0.25.3 is quite old, the latest is 1.1.3.

I upgrade pandas, but I still get the same error.

**Comment by kaukrise** [comment]
Hmm, thanks for posting the version number. I cannot reproduce the issue on my local machine with a sample Cooler file. Could you please try the following in a Python console (`python`):

```
import fanc
print(fanc.__version__)

cool = fanc.load("/path/to/your/file.mcool")
cool.bias_vector()
```

Where you replace the path with the one to the file you are using for CHESS, please?

**Comment by benxiahu** [comment]
>>> import fanc
>>> print(fanc.__version__)
0.9.4
>>> cool = fanc.load("treat.cool")
>>> cool.bias_vector()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nas/longleaf/home/anaconda2/envs/py38/lib/python3.8/site-packages/fanc/compatibility/cooler.py", line 456, in bias_vector
    return np.array([r.bias for r in self.regions(lazy=True)])
  File "/nas/longleaf/home/anaconda2/envs/py38/lib/python3.8/site-packages/fanc/compatibility/cooler.py", line 456, in <listcomp>
    return np.array([r.bias for r in self.regions(lazy=True)])
  File "/nas/longleaf/home/anaconda2/envs/py38/lib/python3.8/site-packages/fanc/compatibility/cooler.py", line 221, in __getattr__
    return getattr(self._series, item)
  File "/nas/longleaf/home/anaconda2/envs/py38/lib/python3.8/site-packages/pandas/core/generic.py", line 5139, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'bias'

**Comment by kaukrise** [comment]
I admit that I don't understand why this is happening. Would you be willing to share your cooler file with me, so that I can do some debugging? Any cooler file I tried, multi- or single-resolution, does not raise an error for this command.

**Comment by benxiahu** [comment]
the cool file is about 5G. I do not think I can share it with you.

I used hicConvertFormat with _--outputFormat cool_ and _--resolutions 10000_  to convert HiC-Pro _normalized_ matrix to .hic format.
Do you think the cool format is right.

**Comment by kaukrise** [comment]
Can you try the following, please?

```python
import fanc
print(fanc.__version__)

cool = fanc.load("/path/to/your/file.mcool")
for r in cool.regions(lazy=True):
    print(r._series.weight)
```

**Comment by kaukrise** [comment]
Alright, I haven't encountered this in a Cooler file yet. Normally, each "bin" in the object has a `weight` property, which is used internally by FAN-C. For some reason, this appears to be missing in your file. Can you please post the output of:

```
import fanc
print(fanc.__version__)

cool = fanc.load("/path/to/your/file.mcool")
for r in cool.regions(lazy=True):
    r._series
    break
```

**Comment by benxiahu** [comment]
>>> for r in cool.regions(lazy=True):
...     print(r._series)
...     break
... 
chrom     chr1
start        0
end      10000
Name: 0, dtype: object

**Comment by kaukrise** [comment]
Thank you. I think I might be able to fix this from within FAN-C. I have uploaded a new FAN-C version (`0.9.5`) to Pypi. It may take a short while to become available, but could you try upgrading with

```
pip3 install --upgrade fanc
```

check that you have the latest version with

```
fanc -V
```

and then try the CHESS command again, please?

**Comment by benxiahu** [comment]
thanks. 
it seems work.
I have another question:
the CHESS takes normalized or raw matrix as input?

**Comment by nickmachnik** [comment]
The input matrices have to be balanced/normalized/corrected, as specified in the cli help and the [docs](https://chess-hic.readthedocs.io/en/latest/cli.html#chess-sim).
I am closing, as the issue seems to be resolved.
