### ISSUE TITLE
ValueError: range() arg 3 must not be zero

### ISSUE THREAD

**Issue by Ferossitiziano** [vaquerizaslab/chess#4]
Good evening,

I am testing chess to compare two .hic matrix that I have obtained with HiCpro.
I am using the following command:

chess sim WT.allValidPairs.hic \
KO.allValidPairs.hic \
mm10_chr2_3mb_win_100kb_step.bed \
WT_vs_KO_chess.tsv

and getting the following error:

Traceback (most recent call last):
  File "/hpcnfs/home/ieo5073/miniconda3/envs/HiCtools/bin/chess", line 548, in <module>
    Chess()
  File "/hpcnfs/home/ieo5073/miniconda3/envs/HiCtools/bin/chess", line 76, in __init__
    getattr(self, args.command)([sys.argv[0]] + sys.argv[option_ix:])
  File "/hpcnfs/home/ieo5073/miniconda3/envs/HiCtools/bin/chess", line 175, in sim
    for chunk in chunks(pairs, threads):
  File "/hpcnfs/home/ieo5073/miniconda3/envs/HiCtools/lib/python3.7/site-packages/chess/helpers.py", line 533, in chunks
    for i in range(0, len(l), n):
ValueError: range() arg 3 must not be zero

Could you please help me with this issue?

Thank you in advance,
Federico

**Comment by nickmachnik** [comment]
Hi Federico,
it looks like there might be no valid pairs in the bed file you provide; there should be a warning about this in the command line logs, could you please provide the full logs here?

**Comment by Ferossitiziano** [comment]
That's the complete logs. You are right, bed file is 1792 lines and none of them are in the contact data.

`````````
2020-10-20 19:37:56,123 INFO Loading reference contact data
2020-10-20 19:37:56,860 INFO Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2020-10-20 19:37:56,860 INFO NumExpr defaulting to 8 threads.
2020-10-20 19:40:21,049 INFO Loading region pairs
2020-10-20 19:40:21,053 WARNING 1792 region pairs have been dropped, because they involve chromosomes that are not present in the provided contact data.
2020-10-20 19:40:21,053 INFO Launching workers
2020-10-20 19:40:21,115 INFO Submitting pairs for comparison
Traceback (most recent call last):
  File "/hpcnfs/home/ieo5073/miniconda3/envs/HiCtools/bin/chess", line 548, in <module>
    Chess()
  File "/hpcnfs/home/ieo5073/miniconda3/envs/HiCtools/bin/chess", line 76, in __init__
    getattr(self, args.command)([sys.argv[0]] + sys.argv[option_ix:])
  File "/hpcnfs/home/ieo5073/miniconda3/envs/HiCtools/bin/chess", line 175, in sim
    for chunk in chunks(pairs, threads):
  File "/hpcnfs/home/ieo5073/miniconda3/envs/HiCtools/lib/python3.7/site-packages/chess/helpers.py", line 533, in chunks
    for i in range(0, len(l), n):
ValueError: range() arg 3 must not be zero
``````````

Thanks a lot for the quick reply, I'll try with a different genomic region.
Best,
Federico
