### ISSUE TITLE
issue of normalized/chess extract

### ISSUE THREAD

**Issue by ZQY19960810** [vaquerizaslab/chess#53]
Hi, author:
When I used chess , I came up with some problems as follows:
First, I want ask do you normalized your .hic fie? If so , could you tell me how to do that? The software or code you achieve that.
Second ,  I have .hic file already ,it produced form Juicer . So could you tell me how extract per chormosome and reslution data form .hic file? Juicertools Pre or dump ?  maybe other software ?
Third , I met some issue , I use hicexplorer hicConvertFormat convert hic to cool
hicConvertFormat -m sample_inter_30.hic --inputFormat hic --outputFormat cool -o ~/opt/juicer/c
hess/sample.cool --resolutions 50000
then , I extract chromosome from .cool
hicConvertFormat -m hub_50000.cool --inputFormat cool --outputFormat cool -o hub_50000.chr1.cool --chromosome 1
and chess pairs and chess sim was worked , but chess extract error(see chess_extract.err File) 
so I tried use normalized by:
hicConvertFormat -m hub_50000.cool --inputFormat cool --outputFormat cool -o hub_50000.chr1.cool --chromosome 1 --correction_name KR
**then chess rxtract not [disruption]() ,but [unfortunately]() I got all nan
there are some files if you need:**
`2022-01-23 17:50:44,884 INFO Running '/home/zhaoqianyi/miniconda3/envs/hicex3.6/bin/chess extract Sscrofa11.1_chr1_3mb_win_100kb_step.bed hub_50000.chr1.cool nmg08_50000.chr1.cool features/'
2022-01-23 17:50:54,086 INFO CHESS version: 0.3.7
2022-01-23 17:50:54,086 INFO FAN-C version: 0.9.21
2022-01-23 17:50:54,090 INFO Loading reference contact data
2022-01-23 17:52:32,215 INFO Loading region pairs
2022-01-23 17:52:32,255 INFO Applying image filtering to identify specific structures
Traceback (most recent call last):
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/bin/chess", line 585, in <module>
    Chess()
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/bin/chess", line 75, in __init__
    getattr(self, args.command)([sys.argv[0]] + sys.argv[option_ix:])
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/bin/chess", line 567, in extract
    args.closing_square)
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/lib/python3.7/site-packages/chess/get_structures.py", line 148, in extract_structures
    filter1 = filters.threshold_otsu(filter_positive, nbins=size)
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/lib/python3.7/site-packages/skimage/filters/thresholding.py", line 364, in threshold_otsu
    counts, bin_centers = _validate_image_histogram(image, hist, nbins)
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/lib/python3.7/site-packages/skimage/filters/thresholding.py", line 307, in _validate_image_histogram
    image.ravel(), nbins, source_range='image', normalize=normalize
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/lib/python3.7/site-packages/skimage/_shared/utils.py", line 338, in fixed_func
    return func(*args, **kwargs)
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/lib/python3.7/site-packages/skimage/exposure/exposure.py", line 267, in histogram
    hist, bin_centers = _histogram(image, nbins, source_range, normalize)
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/lib/python3.7/site-packages/skimage/exposure/exposure.py", line 301, in _histogram
    hist, bin_edges = np.histogram(image, bins=bins, range=hist_range)
  File "<__array_function__ internals>", line 6, in histogram
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/lib/python3.7/site-packages/numpy/lib/histograms.py", line 857, in histogram
    decrement = tmp_a < bin_edges[indices]
IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 61
`
The file named ''Sscrofa11.1_chr1_3mb_win_100kb_step.bed'' foemat like:
![1644375736(1)](https://user-images.githubusercontent.com/76091271/153113929-158ebd2c-f682-4cc7-80cb-2c0482844f41.png)
and my code of chess extract is:
`chess extract Sscrofa11.1_chr1_3mb_win_100kb_step.bed hub_50000.chr1.cool sample_50000.chr1.cool features/
`
THANKS and looking forward for your answering!

**Comment by liz-is** [comment]
Let me see if I'm understanding your various questions correctly.

1. We typically use [FAN-C](https://fan-c.readthedocs.io/), software from our lab, to pre-process Hi-C data, including normalisation using the KR or ICE method. FAN-C is also used internally in CHESS for loading Hi-C data in various formats.

2. You can use Juicer .hic files directly with CHESS. The syntax for accessing a specific resolution and normalisation is shown [here](https://fan-c.readthedocs.io/en/latest/fanc-executable/compatibility.html#juicer-hic-files). You can use FAN-C to subset to a single chromosome as shown [here](https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-generate-hic/fanc_helpers.html#fanc-subset-create-hic-objects-by-subsetting) - you shouldn't need to convert the input Juicer .hic file first, but the output will be in FAN-C .hic format.

3. I don't quite understand what happens here, sorry. Does `chess extract` fail with the IndexError shown above, or does it finish but you don't get any extracted features?
