### ISSUE TITLE
error when running extract on .hic files

### ISSUE THREAD

**Issue by ZQY19960810** [vaquerizaslab/chess#55]
Dear chesser:
Hi, I was using two hic matrices (generated from juicer in resolution 10000, chromosome was all, when I trying to use chess extract command  but shows following error. Do you know the possible reason? Thank you for your answer
Here is the CHESS scripts I hve used:
chess extract Sscrofa11_200kb_win_40kb_step.bed  SAMN15870120.hic@10kb SAMN09691005.hic@10kb ./features

Here is the CHESS error message for the command I have used:
_2022-05-26 21:27:13,658 INFO Running '/home/zhaoqianyi/miniconda3/envs/hicex3.6/bin/chess extract Sscrofa11_200kb_win_40kb_step.bed SAMN15870120.hic@10kb SAMN09691005.hic@10kb ./features'
2022-05-26 21:27:23,521 INFO CHESS version: 0.3.7
2022-05-26 21:27:23,521 INFO FAN-C version: 0.9.23
2022-05-26 21:27:23,525 INFO Loading reference contact data
2022-05-26 22:14:55,429 INFO Loading region pairs
2022-05-26 22:14:55,736 INFO Applying image filtering to identify specific structures
Traceback (most recent call last):
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/bin/chess", line 585, in <module>
    Chess()
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/bin/chess", line 75, in __init__
    getattr(self, args.command)([sys.argv[0]] + sys.argv[option_ix:])
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/bin/chess", line 567, in extract
    args.closing_square)
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/lib/python3.7/site-packages/chess/get_structures.py", line 148, in extract_structures
    filter1 = filters.threshold_otsu(filter_positive, nbins=size)
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/lib/python3.7/site-packages/skimage/filters/thresholding.py", line 364, in threshold_otsu
    counts, bin_centers = _validate_image_histogram(image, hist, nbins)
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/lib/python3.7/site-packages/skimage/filters/thresholding.py", line 307, in _validate_image_histogram
    image.ravel(), nbins, source_range='image', normalize=normalize
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/lib/python3.7/site-packages/skimage/_shared/utils.py", line 338, in fixed_func
    return func(*args, **kwargs)
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/lib/python3.7/site-packages/skimage/exposure/exposure.py", line 266,
in histogram
    hist, bin_centers = _histogram(image, nbins, source_range, normalize)
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/lib/python3.7/site-packages/skimage/exposure/exposure.py", line 300, 
in _histogram
    hist, bin_edges = np.histogram(image, bins=bins, range=hist_range)
  File "<__array_function__ internals>", line 6, in histogram
  File "/home/zhaoqianyi/miniconda3/envs/hicex3.6/lib/python3.7/site-packages/numpy/lib/histograms.py", line 857, in hi
stogram
    decrement = tmp_a < bin_edges[indices]
IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 21_

**Comment by liz-is** [comment]
Hi, this looks like the same issue as encountered here: https://github.com/vaquerizaslab/chess/issues/25

You can try the suggested solutions there. If those don't work, I would need access to a sample of your data that causes this issue in order to debug further.
