### ISSUE TITLE
_pickle.PicklingError

### ISSUE THREAD

**Issue by pengfei50** [vaquerizaslab/chess#57]
Hi,
I want to use chess-hic on my Hi-C data, I successfully installed chess-hic on my own mac following your manual. I generated a pair input file, but I failed to run the search with chess sim with my cool format Hi-C data, could you please give me some comments about the error I met? the commands I used are below:
(chess) a5-phd-mbp :: Ectocarpus_hic/HiC_Matrix/chess-hic » chess sim 561_2k.cool 560_2k.cool v5_win_200kb_step_2000.bed test.tsv
2022-08-09 22:23:47,257 INFO Running '/Users/pliu/miniconda3/envs/chess/bin/chess sim 561_2k.cool 560_2k.cool v5_win_200kb_step_2000.bed test.tsv'
2022-08-09 22:23:48,347 INFO CHESS version: 0.3.7
2022-08-09 22:23:48,347 INFO FAN-C version: 0.9.24
2022-08-09 22:23:48,348 INFO Loading reference contact data
Expected 100% (81203859 of 81203859) |#################################################################################| Elapsed Time: 0:08:54 Time:  0:08:54
2022-08-09 22:46:19,544 INFO Loading query contact data
Expected 100% (60447784 of 60447784) |#################################################################################| Elapsed Time: 0:06:47 Time:  0:06:47
2022-08-09 23:03:07,090 INFO Loading region pairs
2022-08-09 23:03:07,919 INFO Launching workers
Traceback (most recent call last):
  File "/Users/pliu/miniconda3/envs/chess/bin/chess", line 585, in <module>
    Chess()
  File "/Users/pliu/miniconda3/envs/chess/bin/chess", line 75, in __init__
    getattr(self, args.command)([sys.argv[0]] + sys.argv[option_ix:])
  File "/Users/pliu/miniconda3/envs/chess/bin/chess", line 196, in sim
    pool = mp.Pool(threads,
  File "/Users/pliu/miniconda3/envs/chess/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/pliu/miniconda3/envs/chess/lib/python3.10/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/pliu/miniconda3/envs/chess/lib/python3.10/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/pliu/miniconda3/envs/chess/lib/python3.10/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/pliu/miniconda3/envs/chess/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/pliu/miniconda3/envs/chess/lib/python3.10/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/pliu/miniconda3/envs/chess/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/pliu/miniconda3/envs/chess/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/pliu/miniconda3/envs/chess/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/pliu/miniconda3/envs/chess/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'pandas.core.frame.Pandas'>: attribute lookup Pandas on pandas.core.frame failed

**Comment by pengfei50** [comment]
another info, I can run the sample data with chess

**Comment by liz-is** [comment]
If you can run CHESS successfully on the sample data, then I think this is likely an issue with your input data and not with CHESS itself. You could try converting the data to FAN-C .hic format using `fanc hic data.cool data.hic`? Processing of cooler files can be very slow, as they don't store expected values, so this may also be quicker for you in the end.
