### ISSUE TITLE
chess extract error: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by zy041225** [vaquerizaslab/chess#58]
Dear authors,

I'm trying to use `chess extract` to extract the features from the Hi-C matrices of syntenic blocks from different species. However,  it reports errors like:

```
$chess extract HOMSAP.Xref.netFilter.aln.syn.curate.txt.500K.filt target.bed.h5.cool target.bed.h5.cool out/
2022-08-24 19:21:04,391 INFO Loading region pairs
2022-08-24 19:21:04,416 INFO Applying image filtering to identify specific structures
Traceback (most recent call last):
  File "/hwfssz1/ST_EARTH/Reference/ST_DIVERSITY/PUB/USER/zhouyang/software/python-3.9.4/bin/chess", line 585, in <module>
    Chess()
  File "/hwfssz1/ST_EARTH/Reference/ST_DIVERSITY/PUB/USER/zhouyang/software/python-3.9.4/bin/chess", line 75, in __init__
    getattr(self, args.command)([sys.argv[0]] + sys.argv[option_ix:])
  File "/hwfssz1/ST_EARTH/Reference/ST_DIVERSITY/PUB/USER/zhouyang/software/python-3.9.4/bin/chess", line 558, in extract
    extract_structures(
  File "/hwfssz1/ST_EARTH/Reference/ST_DIVERSITY/PUB/USER/zhouyang/software/python-3.9.4/lib/python3.9/site-packages/chess/get_structures.py", line 111, in extract_structures
    or_matrix = np.log(np.divide(query, reference))
ValueError: operands could not be broadcast together with shapes (276,276) (252,252)
```

Could you help me fix this issue?

Many thanks
Yang

**Comment by liz-is** [comment]
Hi,

I'm not super familar with this part of the code, but I'm fairly sure that `chess extract` does not support query and reference regions with different sizes. Sorry that this isn't documented.

I think it would be reasonably simple to add a resizing step if necessary, using the same appraoch as in `chess sim` [here](https://github.com/vaquerizaslab/chess/blob/master/chess/sim.py#L289), but I'm afraid I don't have the time to implement this at the moment. If you do give a go, please let us know - pull requests are welcome :)
